name: Sync to Parent Repo

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:
  sync-to-parent:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the child repo
      - name: Checkout Child Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Step 2: Clone the parent repo
      - name: Clone Parent Repo
        env:
          REPO_TOKEN: ${{ secrets.PARENT_REPO_TOKEN }}  # Add a Personal Access Token (PAT) as a secret
        run: |
          git clone https://x-access-token:${REPO_TOKEN}@github.com/ruhanponnada/hpe.git parent_repo

      # Step 3: Ensure the `api-reference/backup` folder exists
      - name: Create Folder if Missing
        run: |
          mkdir -p parent_repo/api-reference/backup
          echo "Ensured that the 'api-reference/backup' folder exists."

      # Step 4: Sync MDX files and OpenAPI spec to the `api-reference/backup` folder
      - name: Sync Content to Parent Repo
        run: |
          # Sync all markdown files
          rsync -avz --delete ./mdx_files/ parent_repo/api-reference/backup/

          # Copy OpenAPI spec file
          cp ./openapi.json parent_repo/api-reference/backup/openapi.json

          # Verify the contents
          ls -la parent_repo/api-reference/backup/

      # Step 5: Commit and push changes to the parent repo
      - name: Commit Changes to Parent Repo
        run: |
          cd parent_repo
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Sync from child repo: $(date +'%Y-%m-%d %H:%M:%S')" || echo "No changes to commit"
          git push
